// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jkvplbaimsnqpdlzwvfb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImprdnBsYmFpbXNucXBkbHp3dmZiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIyNTc0MjksImV4cCI6MjA1NzgzMzQyOX0.UNgrrwRzPNOocjLhhu4r-yIVlvrxYgj21JPiKMcjRNI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);